### python对象简介

int

In [10]:
n = 5

print(type(n))
print(n.numerator)
print(n.bit_length())
print(n+n, 2*n)
print(n.__sizeof__())           # 调用特殊方法__sizeof__获得内存使用量，以字节为单位


<class 'int'>
5
3
10 10
28


list

In [9]:
l = [1, 2, 3, 4]

print(type(l))
print(l[0])

l.append(10)
print(l+l)
print(2*l)
print(sum(l))
print(l.__sizeof__())

<class 'list'>
1
[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]
[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]
20
104


ndarray

In [20]:
import numpy as np

a = np.arange(16).reshape((4,4))
print(type(a))
print(a.nbytes)
print(a.sum())                  # 有聚合
print(a.cumsum(axis=0))         # 无聚合
print(a+a)

print('-'*30)

print(a.sum())                  
    # print(a.sum()): 这行代码是在使用Pandas库的DataFrame或Series对象时，计算其所有元素的和。在这里，a应该是一个Pandas的DataFrame或Series对象
print(sum(a))                   
    # print(sum(a)): 这行代码是在使用Python内置的sum()函数，它对输入的序列（例如列表，元组等）的所有元素进行求和。在这里，a应该是一个可以迭代的对象，例如列表、元组、字符串等
print(np.sum(a))
    # print(np.sum(a)): 这行代码是在使用Numpy库的sum()函数，它对输入的数组的所有元素进行求和。在这里，a应该是一个Numpy的数组对象
print(a.__sizeof__())

<class 'numpy.ndarray'>
64
120
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
------------------------------
120
[24 28 32 36]
120
128


DataFrame

In [27]:
import pandas as pd
import numpy as np

a = np.arange(16).reshape((4,4))
df = pd.DataFrame(a, columns=list('abcd'))

print(df)
print(type(df))
print(df.columns)
print(df.sum())
print(df.cumsum())

print('-'*30)

print(df + df)
print(2 * df)
print(np.sum(df))
print(df.__sizeof__())

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
<class 'pandas.core.frame.DataFrame'>
Index(['a', 'b', 'c', 'd'], dtype='object')
a    24
b    28
c    32
d    36
dtype: int64
    a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36
------------------------------
    a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30
    a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30
a    24
b    28
c    32
d    36
dtype: int64
196


### python 类基础知识

In [10]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol
        self.__price = price
    
    def get_price(self):
        return self.__price
    
    def set_price(self, price):
        self.__price = price
            # 这段代码是设置一个类的实例变量price的值。
            # self.__price = price是一种常见的在Python类中设置私有变量的方式。
            # 在这个语句中，self是对当前实例的引用，__price是私有变量。私有变量（通常以双下划线前缀命名）通常用于存储不想被外部访问的数据             

class PortfolioPosition(object):

    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    
    def get_position_size(self):
        return self.__position_size
    
    def update_position_size(self, position_size):
        self.__position_size = position_size

    def get_position_value(self):
        return self.__position_size * \
               self.position.get_price()

fi = FinancialInstrument('AAPL', 100)

pp = PortfolioPosition(fi, 10)

pp.get_position_size()

pp.get_position_value()

pp.position.get_price()

pp.position.set_price(105)

pp.position.get_price()

105

### python 数据模型

在Python 2中，所有的类都是从object继承而来的，因此在定义经典类时可以省略object。

但是，在Python 3中，不继承object的类被称为“抽象基类”（Abstract Base Class，简称ABC）。在这种情况下，必须使用abc模块来定义抽象基类，并且需要实现一些特殊的方法（如__subclasshook__和__init_subclass__）。

因此，为了避免潜在的问题，建议在Python 3中定义类时，最好继承自object

In [2]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z

class Vector(Vector):
    def __repr__(self):
        # return f'Vector({self.x, self.y, self.z})' 
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

    def __abs__(self):
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5         # 三个属性值的欧几里得范数

    def __bool__(self):
        return bool(abs(self))

v = Vector(1, 2, -1)
abs(v)
bool(v)

True

In [7]:
class Vector(Vector):
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)

    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)

v = Vector(1, 2, 3)
# v + Vector(2, 3, 4)
# v * 2
v.__add__(Vector(2,3,4))
v.__mul__(5)

Vector(5, 10, 15)

In [34]:
class Vector(Vector):

    def __len__(self):
        return 3

    def __getitem__(self, i):       # __getitem__方法使得类的实例可以像列表一样被索引
        if i in [0, -3] : 
            return self.x
        elif i in [1, -2] : 
            return self.y
        elif i in [2, -1] : 
            return self.z
        else: 
            raise IndexError('Index out of range')

v = Vector(1, 2, 3)

print(len(v))
print(v[0])
print(v[-2])
print(v[-1])
print(v[3])

3
1
2
3


IndexError: Index out of range

In [35]:
class Vector(Vector):

    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

v = Vector(1, 2, 3)

for i in range(3):          # 通过索引值间接迭代(__getitem__)
    print(v[i])

for coordinate in v:        # 在类实例上直接迭代(__iter__)
    print(coordinate)

1
2
3
1
2
3


### Vector 类

In [36]:
class Vector(object):

    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z

    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

    def __abs__(self):
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5

    def __bool__(self):
        return bool(abs(self))

    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)

    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    
    def __len__(self):
        return 3

    def __getitem__(self):
        if i in [0, -3]:
            return self.x
        elif i in [1, -2]:
            return self.y
        elif i in [2,-1]:
            return self.z
        else:
            raise IndexError('Index out of range.')

    def __iter__(self):                         # __iter__方法，它的作用是使得类的实例可迭代
        for i in range(len(self)):
            yield self[i]