### 数组

In [7]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v]
print(m)

print(m[1])
print(m[1][0])

v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]
print(c)
print(c[1][1][0])

[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]
[0.5, 0.75, 1.0, 1.5, 2.0]
0.5
[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]
1


In [8]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
print(m)

v[0] = 'java'
print(m)
# v的改变会直接作用到m

[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]
[['java', 0.75, 1.0, 1.5, 2.0], ['java', 0.75, 1.0, 1.5, 2.0], ['java', 0.75, 1.0, 1.5, 2.0]]


在使用 copy 模块的 deepcopy 函数对某个变量 v 进行深拷贝。deepcopy 函数创建 v 的一个完全独立的副本，这样改变原始 v 的值不会影响到这个副本。

In [9]:
from copy import deepcopy

v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v),]              # 代码 m = 3 * [deepcopy(v),] 的意思是创建一个列表，这个列表包含3个元素，每个元素都是对 v 的深复制。
print(m)

v[0] = 'java'
print(m)

[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]
[[0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0], [0.5, 0.75, 1.0, 1.5, 2.0]]


### array 类

In [10]:
import array

v = [0.5, 0.75, 1.0, 1.5, 2.0]
a = array.array('f', v)
print(a)

a.append(0.5)
# a.append([7,8])           # must be real number, not list
# a.append('str')           # must be real number, not str
a.extend([6.1,9.3])
print(a)

print(2*a)                  # 只是将元素重复，而不是标量乘法

a.tolist()


array('f', [0.5, 0.75, 1.0, 1.5, 2.0])
array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 6.099999904632568, 9.300000190734863])
array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 6.099999904632568, 9.300000190734863, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 6.099999904632568, 9.300000190734863])


[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 6.099999904632568, 9.300000190734863]

### Numpy 数组

In [11]:
import numpy as np

a = np.array([0, 0.5, 1.0, 1.5, 2.0])
print(a)
print(type(a))


b = np.array(['a', 'b', 'c'])
print(b)

c = np.arange(2, 20, 2)
print(c)

d = np.arange(8, dtype=np.float32) 
    # module 'numpy' has no attribute 'float'.     
    # np.float32是浮点数类型的一种在NumPy中，有几种不同的浮点数类型，包括np.float_, np.float16, np.float32, np.float64等，分别对应不同的精度
print(d[5:])
print(d[:2])
print(d.sum(), d.std(), d.cumsum())


[0.  0.5 1.  1.5 2. ]
<class 'numpy.ndarray'>
['a' 'b' 'c']
[ 2  4  6  8 10 12 14 16 18]
[5. 6. 7.]
[0. 1.]
28.0 2.291288 [ 0.  1.  3.  6. 10. 15. 21. 28.]


In [12]:
l = [0, 0.5, 1.0, 1.5, 2.0]
print(2*l)

a = np.array([0, 0.5, 1.0, 1.5, 2.0])
print(2*a)
print(a**2)

print('-'*20)
print(np.exp(a))
print(np.sqrt(a))   

print('-'*20)
print(np.sqrt(25))

import math
print(math.sqrt(25))

# print(math.sqrt(a))           # only length-1 arrays can be converted to Python scalars

print('-'*20)
%timeit np.sqrt(2.5)
%timeit math.sqrt(2.5)          # 浮点数运算上math,sqrt()速度快得多

[0, 0.5, 1.0, 1.5, 2.0, 0, 0.5, 1.0, 1.5, 2.0]
[0. 1. 2. 3. 4.]
[0.   0.25 1.   2.25 4.  ]
--------------------
[1.         1.64872127 2.71828183 4.48168907 7.3890561 ]
[0.         0.70710678 1.         1.22474487 1.41421356]
--------------------
5.0
5.0
--------------------


885 ns ± 86.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
117 ns ± 3.48 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


多维数组

In [13]:
a = np.arange(8, dtype=np.float32)
b = np.array([a,a*2])
print(b)
print(b[0][2])
print(b[0, 2])
print(b[:,1])
print(b.sum(axis=1))
print(b.sum(axis=0))

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 0.  2.  4.  6.  8. 10. 12. 14.]]
2.0
2.0
[1. 2.]
[28. 56.]
[ 0.  3.  6.  9. 12. 15. 18. 21.]


多维数组的计算

括号最大块法有且仅有两步：

    第一步：由axis = value，找对应[]里的最大单位块。（np.sum()拆掉此层[]——求总和 ，np.argmax()不拆此层[]——求最大值的索引）

    第二步：对单位块进行计算，这里又分为两种情况：

        当单位块是数值时，直接计算
        当单位块是数组时，对应下标元素进行计算

使用axis时，不要越界，即：N维数组，最大能使用axis=N-1

https://blog.csdn.net/mahoon411/article/details/114777623

In [14]:
b = np.array([[[1,2,3,4],[1,3,4,5]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]])
print(b)
print('-'*20)
print(b.sum(axis=0))
print('-'*20)
print(b.sum(axis=1))
print('-'*20)
print(b.sum(axis=2))

[[[1 2 3 4]
  [1 3 4 5]]

 [[2 4 7 5]
  [8 4 3 5]]

 [[2 5 7 3]
  [1 5 3 7]]]
--------------------
[[ 5 11 17 12]
 [10 12 10 17]]
--------------------
[[ 2  5  7  9]
 [10  8 10 10]
 [ 3 10 10 10]]
--------------------
[[10 13]
 [18 20]
 [17 16]]


In [15]:
c = np.zeros((2,3), dtype='i', order='C')   
    # dtype='i'：这个参数指定了矩阵中元素的类型为整数。
    # order='C'：这个参数指定了内存中矩阵的存储方式。'C'表示按行存储（行优先），这是默认的方式
print(c)
print('-'*20)

c = np.ones((2,3,4), dtype='i', order='C')
print(c)
print('-'*20)

d = np.zeros_like(c, dtype='float16', order='C')
print(d)
print('-'*20)

d = np.ones_like(c, dtype='float16', order='C')
print(d)
print('-'*20)

[[0 0 0]
 [0 0 0]]
--------------------
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
--------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
--------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
--------------------


In [16]:
e = np.empty((2,3,2))               # np.empty函数创建的是一个未初始化的数组。数组的内容会被填充为某种默认值，这取决于你的数据类型和平台
print(e)
print('-'*20)

f = np.empty_like(c)
print(f)
print('-'*20)

print(np.eye(5))
print('-'*20)

g = np.linspace(5,15,12)            # np.linspace 是 NumPy 库中的一个函数，用于在指定的间隔内返回均匀间隔的数字。 np.linspace(start, end, num)
print(g)

[[[1.09214156e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.01855798e-312 2.59022031e+184]]

 [[6.70632198e+170 1.61610505e+160]
  [2.00335321e-052 9.16930692e-072]
  [1.58770008e-076 5.24648028e+174]]]
--------------------
[[[-1389032376         514          64           0]
  [          0           0           0           0]
  [          0          48   808476979  1714971193]]

 [[ 1680945254  1667642980   912471094  1630692450]
  [  811872560   892547125   878798389   825242469]
  [  859386677   808608354   845504817  1681208930]]]
--------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
--------------------
[ 5.          5.90909091  6.81818182  7.72727273  8.63636364  9.54545455
 10.45454545 11.36363636 12.27272727 13.18181818 14.09090909 15.        ]


# 元信息

In [17]:
g = np.linspace(5,15,12)   

print(g.size)
print('-'*20)

print(g.itemsize)       # 用于表示一个元素的字节数
print('-'*20)

print(g.shape)
print('-'*20)

print(g.dtype)
print('-'*20)

print(g.nbytes)         # 在内存中使用的字节总数


12
--------------------
8
--------------------
(12,)
--------------------
float64
--------------------
96


改变组成

In [18]:
g = np.arange(15)
print(g)
print('-'*20)
print(g.shape)
print(np.shape(g))
print('-'*20)

h = g.reshape((3,5))
print(h)
print('-'*20)
print(h.T)      # h.transpose()
print('-'*20)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
--------------------
(15,)
(15,)
--------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
--------------------


改变大小

In [19]:
g = np.arange(15)

# 缩小二维数组
print(np.resize(g, (3, 1)))     
print('-'*20)

print(np.resize(g, (1, 5)))
print('-'*20)

# 扩大二维数组
print(np.resize(g, (5, 4)))

[[0]
 [1]
 [2]]
--------------------
[[0 1 2 3 4]]
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14  0]
 [ 1  2  3  4]]


堆叠

In [20]:
g = np.arange(15)
h = g.reshape((5,3))

print(np.hstack((h, h*2)))
print('-'*20)
print(np.vstack((h, h*2)))
print('-'*20)
print(np.dstack((h, h*2)))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]
 [ 9 10 11 18 20 22]
 [12 13 14 24 26 28]]
--------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]
--------------------
[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]

 [[ 9 18]
  [10 20]
  [11 22]]

 [[12 24]
  [13 26]
  [14 28]]]


扁平化

C order 指的是 Row-major Order

![Alt text](image.png)

F order 指的是 Column-major Order

![Alt text](image-2.png)

In [43]:
g = np.arange(15)
h = g.reshape((5,3))
print(h.flatten())
print(h.flatten(order='C'))         # 以C顺序（默认）进行扁平化
print(h.flatten(order='F'))         # 以F顺序进行扁平化
print('-'*50)

for i in h.flat:
    print(i, end=',')               # end=',是设置输出不换行，而是以逗号作为结束字符

for i in h.ravel(order='C'):        # ravel()是一个NumPy库中的函数，用于将多维数组转换为一维数组；与flat相似，但可指定以行存储还是列存储
    print(i, end=';')

for i in h.ravel(order='F'):
    print(i, end='.')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  3  6  9 12  1  4  7 10 13  2  5  8 11 14]
--------------------------------------------------
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;0.3.6.9.12.1.4.7.10.13.2.5.8.11.14.

布尔数组   

    and —— &
    or —— |

In [22]:
g = np.arange(15)
h = g.reshape((5,3))

print(h > 8)
print('-'*20)

print((h == 5).astype(int))
print('-'*20)

print()


[[False False False]
 [False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
--------------------
[[0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
--------------------



布尔数组可用于索引和数据的选择

In [23]:
g = np.arange(15)
h = g.reshape((5,3))

print(h[h > 8])
print(h[(h > 8) & (h <= 12)])
print(h[(h < 4) | (h >= 12)])

[ 9 10 11 12 13 14]
[ 9 10 11 12]
[ 0  1  2  3 12 13 14]


np.where()

    numpy.where(condition[, x, y])
    x, y：这两个参数是可选的。如果提供，它们必须是具有相同形状和类型的一维或二维数组。在条件为真时返回x，在条件为假时返回y

In [24]:
print(np.where(h>7, 1, 0))

print(np.where(h%2==0, 'even', 'odd'))

print(np.where(h<=7, h*2, h/2))

[[0 0 0]
 [0 0 0]
 [0 0 1]
 [1 1 1]
 [1 1 1]]
[['even' 'odd' 'even']
 ['odd' 'even' 'odd']
 ['even' 'odd' 'even']
 ['odd' 'even' 'odd']
 ['even' 'odd' 'even']]
[[ 0.   2.   4. ]
 [ 6.   8.  10. ]
 [12.  14.   4. ]
 [ 4.5  5.   5.5]
 [ 6.   6.5  7. ]]


速度对比

第一种，使用嵌套列表形成矩阵——list

In [25]:
import random

I = 5000
%time mat = [[random.gauss(0,1) for j in range(I)]  for i in range(I)]          # 通过嵌套列表的推到来创建矩阵：5000 x 5000的二维数组

CPU times: total: 20.4 s
Wall time: 20.6 s


In [26]:
type(mat)

list

In [27]:
mat[0][:5]

%time sum([sum(l) for l in mat])                # 在列表推导期间首先计算单个列表对象的总和，然后取这些总和的总和

CPU times: total: 359 ms
Wall time: 413 ms


-2054.513546727786

In [28]:
import sys

sum([sys.getsizeof(l) for l in mat])            # sys.getsizeof(l)：这个函数返回传入对象的内存占用大小（单位为字节）

209400000

第二种，使用ndarray——速度比第一种快了二十倍，内存占用也小

In [2]:
import numpy as np

I = 5000
%time mat = np.random.standard_normal((I,I))

CPU times: total: 766 ms
Wall time: 765 ms


In [30]:
type(mat)

numpy.ndarray

In [31]:
%time mat.sum()

CPU times: total: 156 ms
Wall time: 163 ms


9635.782086440367

In [32]:
mat.nbytes

200000000

In [33]:
import sys

sys.getsizeof(mat)

200000128

### Numpy结构数组

In [34]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])    
    # NumPy数据类型（dtype）的定义，用于描述一个复合数据类型

    # 'Name': 是一个长度最大为10的字节字符串（'S10'）。这可以用来存储人类的名字，例如 'John' 或 'Alexandru'.
    # 'Age': 是一个4字节的整数（'i4'）。这可以用来存储年龄，例如25或30。
    # 'Height': 是一个浮点数（'f'）。这可以用来存储身高，例如1.75或1.80。
    # Children/Pets': 是一个2个元素的整数数组（'i4', 2）。这可以用来存储孩子或宠物的数量，例如 [2, 3] 可以表示有2个孩子和3只宠物。
print(dt)

s = np.array([('Smith', 45, 1.83, (0,1)), ('Jones', 53, 1.72, (2,2))], dtype=dt)        # 实现结构化数组
print(s)
print(type(s))

[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))]
[(b'Smith', 45, 1.83, [0, 1]) (b'Jones', 53, 1.72, [2, 2])]
<class 'numpy.ndarray'>


In [35]:
print(s['Name'])

print(s['Height'].mean())

print(s[0])

print(s[1]['Age'])

[b'Smith' b'Jones']
1.7750001
(b'Smith', 45, 1.83, [0, 1])
53


### 代码向量化

In [36]:
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * 0.5

print(r)
print('')
print(r+s)
print('')
print(r*2 + 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0.   1.5  3. ]
 [ 4.5  6.   7.5]
 [ 9.  10.5 12. ]
 [13.5 15.  16.5]]

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]
 [21 23 25]]


ndarray的运算

https://blog.csdn.net/tust123qht/article/details/84779766

In [5]:
r = np.arange(12).reshape((4,3))

s = np.arange(0, 12, 4)

print(r+s)

m = np.arange(0, 12, 3)

print(r.T+m)

mr = m.reshape(-1, 1)           
    # -1指未设定行数
    # reshape(-1, 1) 表示（任意行，1列） eg.4行4列变成16行1列
    # reshape(-1, 2) 表示（任意行，2列） eg.4行4列变成8行2列
    # reshape(1, -1) 表示（1行，任意列） eg.4行4列变成1行16列
print(mr)
print(mr.shape)
print(m)

[[ 0  5 10]
 [ 3  8 13]
 [ 6 11 16]
 [ 9 14 19]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]]
[[0]
 [3]
 [6]
 [9]]
(4, 1)
[0 3 6 9]


numpy 不同形状(shape)的数组数值计算方式

https://blog.csdn.net/t852947739/article/details/89219378

1.如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。 

In [38]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = a * b
print(c)

[ 5 12 21 32]


2.当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。

![Alt text](image-3.png)

np.tile是NumPy库中的一个函数，用于重复数组（或数组的一部分）以生成新的数组。

    基本语法是：numpy.tile(A, reps)
    这里，A是输入数组，reps是一个整数或整数数组，定义了A应被复制多少次。

In [39]:
import numpy as np 
	     
a = np.array([[ 0, 0, 0],
            [10,10,10],
            [20,20,20],
            [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [12]:
import numpy as np
a = np.array([[ 0, 0, 0], [10,10,10], [20,20,20], [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))
print(a + bb)
print(bb)

cc = np.tile(b, (4, 4))
print(cc)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3 1 2 3]]


In [44]:
import numpy as np

a = np.array([0, 1, 2])
b = np.tile(a,2)
print(b)
print('***********************')
c = np.tile(a, (2, 1))     
print (c)
print('***********************')
d = np.tile(a, (2, 2, 1))      
print(d)
print('***********************')
e = np.array([[1, 2], [3, 4]])
f = np.tile(e, 2)        
print(f)
print('***********************')
g = np.tile(e, (2, 1))    
print(g)
print('***********************')
h = np.array([1,2,3,4])
i = np.tile(h,(4,1))      
print(i)


[0 1 2 0 1 2]
***********************
[[0 1 2]
 [0 1 2]]
***********************
[[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]]
***********************
[[1 2 1 2]
 [3 4 3 4]]
***********************
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
***********************
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


内存布局

In [15]:
x = np.random.standard_normal((1000000, 5))

y = 2 * x + 3

C = np.array((x,y), order='C')

F = np.array((x,y), order='F')

x = 0.0
y = 0.0         # 释放内存

print(C[:2].round(2))
print(F[:2].round(2))

# %timeit C.sum()

[[[-2.62  0.63 -0.06 -0.56  0.61]
  [ 0.78  0.18 -0.06 -0.55  0.66]
  [-0.71  0.27 -0.09 -0.35 -0.01]
  ...
  [-1.53  0.22 -0.63 -1.45  0.54]
  [ 1.56 -2.09 -1.09  0.46 -0.01]
  [ 0.03  0.66  0.5   1.03 -0.09]]

 [[-2.25  4.27  2.87  1.87  4.23]
  [ 4.55  3.36  2.87  1.91  4.33]
  [ 1.57  3.54  2.82  2.29  2.98]
  ...
  [-0.05  3.45  1.75  0.09  4.09]
  [ 6.13 -1.19  0.83  3.92  2.99]
  [ 3.06  4.31  4.    5.05  2.83]]]
[[[-2.62  0.63 -0.06 -0.56  0.61]
  [ 0.78  0.18 -0.06 -0.55  0.66]
  [-0.71  0.27 -0.09 -0.35 -0.01]
  ...
  [-1.53  0.22 -0.63 -1.45  0.54]
  [ 1.56 -2.09 -1.09  0.46 -0.01]
  [ 0.03  0.66  0.5   1.03 -0.09]]

 [[-2.25  4.27  2.87  1.87  4.23]
  [ 4.55  3.36  2.87  1.91  4.33]
  [ 1.57  3.54  2.82  2.29  2.98]
  ...
  [-0.05  3.45  1.75  0.09  4.09]
  [ 6.13 -1.19  0.83  3.92  2.99]
  [ 3.06  4.31  4.    5.05  2.83]]]
